version: '2'
services:
  ecb-web-client:
    container_name: ui
    build:
      context: .
    environment:
      - EBC_API_URI=http://192.168.0.172
      - AZURE_CLIENT_ID=0f297dc1-bee5-4c1f-92a6-043286710fd1
      - AZURE_AUTHORITY=https://login.microsoftonline.com/2b5438a9-6a60-437b-afb7-2cc6fd444d86
      - AZURE_REDIRET_URI=http://localhost:3000,
      - AZURE_CACHE_LOCATION=localStorage
    ports:
      - 3000:80
